baseURL: "https://example.org"
languageCode: "en-us"
title: "Tatsuhiko Kato"
theme: "hugo-profile"

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: ブログ
      title: Blog posts
      url: /blogs
      weight: 1

params:
  title: "Tatsuhiko Kato"
  description: Azure やC#、React が得意なウェブデベロッパーです！
  # favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor: 
  #   secondaryTextColor: 
  #   backgroundColor: 
  #   secondaryBackgroundColor: 
  #   primaryColor: 
  #   secondaryColor: 

  #   darkmode:
  #     textColor: 
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    # intro: "Hi, my name is"
    title: "加藤龍彦 / Tatsuhiko Kato"
    subtitle: "Web Developer"
    content: "Azure やC#、React に強いウェブデベロッパーです。現所属：[CData Software Japan](https://www.cdata.com/jp)"
    # image: /images/hero.svg
    button:
      enable: false
      name: "経歴"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/fiction000/
        - icon: fab fa-twitter
          url: https://twitter.com/hastur_kato/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/kato-tatsuhiko
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"


  # About
  about:
    enable: true
    title: "スキルセット"
    # image: '/images/me.png'
    content: |-
     
    skills:
      enable: true
      title: "業務で使用してきた技術です："
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Azure (VM, DevOps)"
        - "C#"
        - "ASP.NET"
        - "Node"
        - "Git"

  # Experience
  experience:    
    enable: true
    title: "経歴"
    items:
      - job: "Web Developer"
        company: "CData Software Japan"
        companyUrl: "https://cdata.com/jp"
        date: "2020年10月 〜 現在"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: ""
        
  # Education
  education:
    enable: true
    title: "学歴"
    # index: true
    items:
      - title: "Master of Science"
        school:
          name: "北陸先端科学技術大学院大学"
          url: "https://jaist.ac.jp/"
        date: "2017 - 2019"
        content: |-          
          研究内容：自然言語処理の技術（単語埋め込みモデル）とヒトの（特に子どもの）知識獲得の過程の類似点・差異、その原因について研究していました。
          研究発表
          - 
      - title: "哲学士"
        school:
          name: "慶應義塾大学"
          url: "https://keio.ac.jp"
        date: "2012 - 2017"
        content: |-
            
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      
  # Achievements
  achievements:
    enable: false
    items:  
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: パーソナルビジネスカード
        content: React で自分用のビジネスカードを作りました。
        image: /images/projects/profile.png
        featured:
          name: デモ
          link: https://hugo-profile.netlify.app
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile
      
  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/fiction000/
      linkedin: https://www.linkedin.com/in/kato-tatsuhiko
      twitter: https://twitter.com/hastur_kato

